OnlineDisscussionForum FYP/OnlineDisscussionForum/Models/Post/NewPostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineDisscussionForum.Models.Post
{
    public class NewPostModel
    {
       public string ForumName { get; set; }
        public int ForumId { get; set; }
        public string AuthorName { get; set; }
        public string ForumImageUrl { get; set; }

        public string Title { get; set; }
        public string Content { get; set; }
    }
}

OnlineDisscussionForum FYP/OnlineDisscussionForum/Models/Post/PostIndexModel.cs
using System;
using System.Collections.Generic;
using OnlineDisscussionForum.Models.Reply;

namespace OnlineDisscussionForum.Models.Post
{
    public class PostIndexModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating { get; set; }
        public string AuthorImageUrl { get; set; }
        public DateTime Created { get; set; }
        public string PostContent { get; set; }
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public bool IsAuthorAdmin { get; set; }
        public IEnumerable<PostReplyModel> Replies { get; set; }
    }
}

OnlineDisscussionForum FYP/OnlineDisscussionForum/Models/Post/PostListingModel.cs
using OnlineDisscussionForum.Models.Forum;

namespace OnlineDisscussionForum.Models.Post
{
    public class PostListingModel
    {
       public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating{ get; set; }
        public string AuthorId { get; set; }
        public string DatePosted { get; set; }
       

        public ForumListingModel Forum { get; set; }

        public int RepliesCount { get; set; }
    }
}

OnlineDisscussionForum FYP/OnlineDisscussionForum/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineDisscussionForum.Data;
using OnlineDisscussionForum.Data.Models;
using OnlineDisscussionForum.Models.Post;
using OnlineDisscussionForum.Models.Reply;

namespace OnlineDisscussionForum.Controllers
{
   
    public class PostController : Controller
    {
        private readonly IPost _postService;
        private readonly IForum _forumService;
        private readonly IApplicationUser _userService;
        private static UserManager<ApplicationUser> _userManager;
        public PostController(IPost postService, IForum forumService,UserManager<ApplicationUser> userManager, IApplicationUser userService)
        {
            _postService = postService;
            _forumService = forumService;
            _userManager = userManager;
            _userService = userService;
        }

        public IActionResult Index(int id)
            
        {
            var post = _postService.GetById(id);
            var replies = BuildPostReplies(post.Replies);
            var model = new PostIndexModel
            {
                Id = post.Id,
                Title = post.Title,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorImageUrl = post.User.ProfileImageUrl,
                AuthorRating = post.User.Rating,
                Created = post.Created,
                PostContent = post.Content,
                Replies = replies,
                ForumId = post.Forum.Id,
                ForumName = post.Forum.Title,
                IsAuthorAdmin = IsAuthorAdmin(post.User)


            };
            return View(model);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddPost(NewPostModel model)
        {
            var userId = _userManager.GetUserId(User);
            var user =  _userManager.FindByIdAsync(userId).Result;
            var post = BuildPost(model, user);
            await _postService.Add(post);
            await _userService.UpdateUserRating(userId, typeof(Post));
            return RedirectToAction("Index", "Post", new { id = post.Id });
        }

        private Post BuildPost(NewPostModel model, ApplicationUser user)
        {
            var forum = _forumService.GetById(model.ForumId);
            return new Post
            {
                Title = model.Title,
                Content = model.Content,
                Created = DateTime.Now,
                User = user,
                Forum = forum
            };
        }
        [Authorize]
        public IActionResult Create(int id)
        {
            var forum = _forumService.GetById(id);
            var model = new NewPostModel
            {
                ForumName = forum.Title,
                ForumId = forum.Id,
                ForumImageUrl = forum.ImageUrl,
                AuthorName = User.Identity.Name

            };
                return View(model);
        }

        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(reply => new PostReplyModel
            {
                Id = reply.Id,
                AuthorId = reply.User.Id,
                AuthorName = reply.User.UserName,
                AuthorImageUrl = reply.User.ProfileImageUrl,
                AuthorRating = reply.User.Rating,
                Created = reply.Created,
                ReplyContent = reply.Content,
                IsAuthorAdmin = IsAuthorAdmin(reply.User)





            });
        }
        private bool IsAuthorAdmin(ApplicationUser user)
        {
            return _userManager.GetRolesAsync(user).Result.Contains("Admin");
        }

    }
}

OnlineDisscussionForum FYP/OnlineDisscussionForum/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineDisscussionForum.Data;
using OnlineDisscussionForum.Models.Reply;
using OnlineDisscussionForum.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace OnlineDisscussionForum.Controllers
{
    [Authorize]
    public class ReplyController : Controller
    {
        private readonly IPost _postService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUser _userService;
       public ReplyController(IPost postService, UserManager<ApplicationUser> userManager, IApplicationUser userService)
        {
            _postService = postService;
            _userManager = userManager;
            _userService = userService;
        }

        public async Task<IActionResult> Create(int id)
        {
            var post = _postService.GetById(id);
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var model = new PostReplyModel
            {
                PostContent = post.Content,
                PostTitle = post.Title,
                PostId = post.Id,

                AuthorId = user.Id,
                AuthorName = User.Identity.Name,
                AuthorImageUrl = user.ProfileImageUrl,
                AuthorRating = user.Rating,
                IsAuthorAdmin = User.IsInRole("Admin"),

                ForumName = post.Forum.Title,
                ForumId = post.Forum.Id,
                ForumImageUrl = post.Forum.ImageUrl,

                Created = DateTime.Now
               

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddReply(PostReplyModel model)
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);
            var reply = BuildReply(model, user);
            await _postService.AddReply(reply);
            await _userService.UpdateUserRating(userId, typeof(PostReply));
            return RedirectToAction("Index", "Post", new { id = model.PostId });
        }

        private PostReply BuildReply(PostReplyModel model, ApplicationUser user)
        {
            var post = _postService.GetById(model.PostId);
            return new PostReply
            {
                Post = post,
                Content = model.ReplyContent,
                Created = DateTime.Now,
                User = user
            };
        }
    }
}

OnlineDisscussionForum FYP/OnlineDisscussionForum/Views/Post/Create.cshtml
@model OnlineDisscussionForum.Models.Post.NewPostModel


<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading noBorder">
            New Post | @Model.ForumName
            <div class="forumLogo" style="background-image:url(@Model.ForumImageUrl)"></div>
            <span id="headingBtn">
                <a asp-controller="Forum"asp-action="topic" asp-route-id="@Model.ForumId" class="btn btn-back">
                   Back to @Model.ForumName
                  </a>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="createPostSection">
            <div class="authorBlock">
                You're submitting this post as <strong>@Model.AuthorName</strong>
            </div>
            <form asp-action="AddPost" method="post" id="addPostForm">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Content"></label>
                    <textarea asp-for="Content" class="form-control" rows="20"></textarea>
                </div>
                <button type="submit" id="submitPostBtn" class="btn btn-submitPost">
                    Submit Post
                </button>
                <input asp-for="ForumId" type="hidden"/>
            </form>
        </div>
    </div>
</div>




@*<h1>New Post |  @Model.ForumName</h1>

<form asp-action="AddPost" method="post" id="addPostForm">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />

    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" class="form-control" ></textarea>

    </div>
    <button type="submit" id="submitPostBtn" class="btn btn-submitPost">Submit Post</button>
    <input asp-for="ForumId" type="hidden" />


</form>*@

OnlineDisscussionForum FYP/OnlineDisscussionForum/Views/Post/Index.cshtml
@model OnlineDisscussionForum.Models.Post.PostIndexModel


<div class="container body-content">
    <div class="row postHeader">
        <div class="postHeading">
            <span class="postIndexTitle">
                @Model.Title

            </span>
            <span id="headingBtn"><a asp-controller="Forum" asp-action="Topic" asp-route-id="@Model.ForumId" class="btn btn-back">Back to @Model.ForumName </a></span>
        </div>

    </div>

    <div class="row" id="postIndexContent">
        <div class="col-md-3 postAuthorContainer">
            <div class="postAuthorImage" style="background-image:url(@Model.AuthorImageUrl);"></div>
            <a asp-controller="Profile" asp-action="Detail" asp-route-id="@Model.AuthorId">
                @Model.AuthorName

            </a>
            <span class="postData">@Model.Created</span>
            @if (Model.IsAuthorAdmin)
            {
                <span class="isAdmin smaller">Admin</span>
            }
        </div>
        <div class="col-md-9 postContentContainer">
            <div class="postContent">
                @Html.Raw(Model.PostContent)

            </div>
        </div>
    </div>



    <div class="row" id="replyDivider"></div>


    @if (User.Identity.IsAuthenticated)

    {
        <div class="row" id="postReplyRow">
            <span>
                <a asp-controller="Reply" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-newReply">
                    Post Reply
                </a>
            </span>
        </div>

    }
    @if (Model.Replies.Any())
    {
        foreach (var reply in Model.Replies)
        {
            <div class="row replyContent">
                <div class="col-md-3 replyAuthorContainer">
                    <div class="postAuthorImage" style="background-image:url(@reply.AuthorImageUrl)"></div>
                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@reply.AuthorId">
                        @reply.AuthorName
                    </a>
                    @if (reply.IsAuthorAdmin)
                    {
                        <div class="isAdmin smaller">Admin</div>
                        <br />
                    }
                    <span class="postDate">@reply.Created</span>
                </div>
                <dv class="col-md-9 replyContentContainer">
                    <div class="postContentContainer">
                        @Html.Raw(reply.ReplyContent)

                    </div>
                </dv>
            </div>
        }

    }
    else
    {
            <div class="row" id="forumIndexContent">
                <div class="noPosts">
                    <h3>
                        There are no replies to this post.<br />
                    </h3>
                </div>
            </div>
    }
 </div>

    @*<h1>@Model.Title</h1>
        <div>
            Author: @Model.AuthorName (@Model.AuthorRating)
            Created: @Model.Created
        </div>

        <div>
            @Model.PostContent
        </div>

        @if(Model.Replies.Any())
        {
            foreach(var reply in Model.Replies)
            {
        <div>
            <div>
                Reply Author: @reply.AuthorName
                Reply Created: @reply.Created
            </div>

            <div>
               Reply: @reply.ReplyContent
            </div>

        </div>
            }
        }*@